In [1]:
import numpy as np

class Launching():
  def np_abs(self, array, slicing=None):
    if slicing is not None:
      array[slicing[0], :slicing[1]] = 0
      array[slicing[0], slicing[1]+1:] = 0
      if slicing[0] == 0:
        array[slicing[0]+1] = 0
      else:
        array[slicing[0]-1] = 0
    print('ABS', np.abs(array[slicing]))

  def np_sin(self, array, slicing=None):
    if slicing is not None:
      array[slicing[0], :slicing[1]] = 0
      array[slicing[0], slicing[1]+1:] = 0
      if slicing[0] == 0:
        array[slicing[0]+1] = 0
      else:
        array[slicing[0]-1] = 0
    print('SIN', np.sin(array[slicing]))

  def np_sqrt(self, array, slicing=None):
    if slicing is not None:
      array[slicing[0], :slicing[1]] = 0
      array[slicing[0], slicing[1]+1:] = 0
      if slicing[0] == 0:
        array[slicing[0]+1] = 0
      else:
        array[slicing[0]-1] = 0
    print('SQRT', np.sqrt(array[slicing]))

  def np_square(self, array, slicing=None):
    if slicing is not None:
      array[slicing[0], :slicing[1]] = 0
      array[slicing[0], slicing[1]+1:] = 0
      if slicing[0] == 0:
        array[slicing[0]+1] = 0
      else:
        array[slicing[0]-1] = 0
    print('SQUARE', np.square(array[slicing]))
  
  def array_3D(self, np_array):
    i=1
    while True:
      i+=1
      if len(np_array[0]) % i == 0:
        a=i
        break
    return np_array.reshape(int(len(np_array[0])/a), a, 2)

arr = np.random.randint(0, 20, size=(2, 30))
 
Launching().np_square(arr, (1, 5))
print(arr)

arr1 = np.random.randint(0, 25, size=(2, 45))
 
arr1 = Launching().array_3D(arr1)
print(arr1)



SQUARE 4
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[[[16 10]
  [17 13]
  [20  2]]

 [[ 3 24]
  [13 23]
  [ 9 10]]

 [[ 1  2]
  [ 7 22]
  [23 24]]

 [[12 23]
  [16  6]
  [ 1 13]]

 [[17 22]
  [21  6]
  [17 16]]

 [[ 3  5]
  [ 1  1]
  [15 13]]

 [[14  0]
  [17 18]
  [22 22]]

 [[ 3 24]
  [17 24]
  [12 18]]

 [[13  4]
  [ 6 12]
  [19  0]]

 [[19 24]
  [ 1 21]
  [21  5]]

 [[14  1]
  [10 23]
  [14 10]]

 [[ 4 11]
  [ 1  4]
  [ 8 20]]

 [[ 0  8]
  [18 24]
  [ 7 17]]

 [[21  7]
  [24 10]
  [ 3 22]]

 [[ 0 18]
  [12 10]
  [17  5]]]
